version: '3'
services:
  front:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - .:/myapp:delegated
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    working_dir: /myapp
    command: sh -c "yarn install && yarn dev"
    stdin_open: true
    tty: true
volumes:
  yarn-cache: